### ISSUE TITLE
chapter3/Horse_or_Human_WithAugmentation.ipynb - same files used for train and validation

### ISSUE THREAD

**Issue by Sturzgefahr** [lmoroney/tfbook#5]
Hi,

Before I forget, thanks again for writing these tutorials.  I'm finding them extremely helpful as I prepare for the TF Developer's Exam.

In chapter3, the URLs for the train and validation sets in `Horse_or_Human_WithAugmentation.ipynb` both point to the same zip file.  

```
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/horse-or-human.zip \
    -O /tmp/horse-or-human.zip

!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/horse-or-human.zip \
    -O /tmp/validation-horse-or-human.zip
```

The URL for the validation set is likely this one:

```
https://storage.googleapis.com/laurencemoroney-blog.appspot.com/validation-horse-or-human.zip 
```

There's also a typo a few cells below.

```
validation_generator = train_datagen.flow_from_directory(
        '/tmp/vallidation-horse-or-human',  # should be 'validation'
        target_size=(300, 300),
        class_mode='binary')

```

`'/tmp/vallidation-horse-or-human',` should be `'/tmp/validation-horse-or-human',`.

Cheers,

- MC

**Comment by lmoroney** [comment]
Thanks! Should be fixed now.
